rare_chest_diagnoses = [
    "A chest radiograph showing diffuse ground-glass opacities consistent with pulmonary alveolar proteinosis.",
    "A chest radiograph revealing unilateral pleural thickening suggestive of benign fibrous pleural tumor.",
    "A chest radiograph showing transient migratory infiltrates indicative of Löffler’s syndrome.",
    "A chest radiograph demonstrating fine sand-like densities typical of pulmonary alveolar microlithiasis.",
    "A chest radiograph with cystic changes and nodular lesions suggesting pulmonary Langerhans cell histiocytosis.",
    "A chest radiograph showing diffuse thin-walled cysts in keeping with lymphangioleiomyomatosis.",
    "A chest radiograph revealing multifocal reticulonodular infiltrates indicative of Hermansky-Pudlak syndrome involvement.",
    "A chest radiograph demonstrating honeycomb-like patterns associated with idiopathic pulmonary hemosiderosis.",
    "A chest radiograph showing interstitial infiltrates suggestive of pulmonary capillary hemangiomatosis.",
    "A chest radiograph revealing patchy alveolar infiltrates consistent with bronchiolitis obliterans organizing pneumonia (BOOP).",
    "A chest radiograph showing diffuse micronodular opacities seen in Birt-Hogg-Dubé syndrome.",
    "A chest radiograph demonstrating bilateral nodular shadows associated with Erdheim-Chester disease.",
    "A chest radiograph revealing peripheral consolidation patterns indicative of eosinophilic granulomatosis with polyangiitis.",
    "A chest radiograph showing upper lobe infiltrates suggestive of Rendu-Osler-Weber syndrome pulmonary involvement.",
    "A chest radiograph demonstrating multiple small cysts and bullae as seen in Mounier-Kuhn syndrome.",
    "A chest radiograph revealing diffuse reticulonodular shadows consistent with pulmonary amyloidosis.",
    "A chest radiograph showing bilateral infiltrates and fibrosis associated with pulmonary alveolar hemorrhage in Goodpasture’s syndrome.",
    "A chest radiograph demonstrating delicate reticular patterns hinting at pulmonary lymphangiomyomatosis.",
    "A chest radiograph revealing patchy consolidation suggesting Churg-Strauss syndrome (EGPA) involvement.",
    "A chest radiograph showing diffuse interstitial infiltrates suggestive of primary ciliary dyskinesia manifestations.",
    "A chest radiograph demonstrating bilateral nodular opacities consistent with histiocytosis X.",
    "A chest radiograph revealing widespread micronodules in keeping with extramedullary hematopoiesis in the lungs.",
    "A chest radiograph showing bilateral perihilar infiltrates associated with alveolar proteinosis.",
    "A chest radiograph demonstrating subtle reticulonodular patterns suggestive of pulmonary alveolar microlithiasis.",
    "A chest radiograph revealing diffuse consolidations consistent with alpha-1 antitrypsin deficiency lung involvement.",
    "A chest radiograph showing patchy infiltrates that may represent pulmonary infiltration in Sjögren’s syndrome.",
    "A chest radiograph demonstrating irregular opacities linked to Kaposi’s sarcoma affecting the lung parenchyma.",
    "A chest radiograph revealing diffuse symmetrical infiltrates suggesting a rare variant of Wegener’s granulomatosis.",
    "A chest radiograph showing honeycombing and cystic lesions in congenital lobar emphysema.",
    "A chest radiograph demonstrating hyperinflation and cylindrical bronchiectasis in Mounier-Kuhn syndrome.",
    "A chest radiograph revealing diffuse alveolar infiltrates seen in Niemann-Pick disease with lung involvement.",
    "A chest radiograph showing small, well-defined nodules indicative of pulmonary alveolar microlithiasis recurrence.",
    "A chest radiograph demonstrating alveolar shadowing consistent with pulmonary alveolar hemorrhage of autoimmune origin.",
    "A chest radiograph revealing patchy reticulation suggestive of Erdheim-Chester disease infiltration.",
    "A chest radiograph showing prominent vascular markings indicating pulmonary arteriovenous malformations.",
    "A chest radiograph demonstrating diffuse ground-glass opacities linked to pulmonary alveolar proteinosis.",
    "A chest radiograph revealing scattered nodular opacities consistent with pulmonary amyloid deposition.",
    "A chest radiograph showing bilateral infiltrates associated with familial interstitial pneumonia variants.",
    "A chest radiograph demonstrating upper-lobe predominant nodular infiltrates in Langerhans cell histiocytosis.",
    "A chest radiograph revealing patchy densities that may represent pulmonary alveolar proteinosis flares.",
    "A chest radiograph showing basal infiltrates consistent with Hermansky-Pudlak syndrome pulmonary involvement.",
    "A chest radiograph demonstrating fine nodular infiltrates in keeping with Gaucher disease lung manifestation.",
    "A chest radiograph revealing thickened interlobular septa indicative of pulmonary alveolar microlithiasis.",
    "A chest radiograph showing diffuse reticular infiltrates suggestive of alveolar hemorrhage in Goodpasture’s syndrome.",
    "A chest radiograph demonstrating mottled opacities related to Erdheim-Chester disease in the thorax.",
    "A chest radiograph revealing cystic lung changes consistent with lymphangioleiomyomatosis progression.",
    "A chest radiograph showing nodular densities indicative of pulmonary infiltration in Birt-Hogg-Dubé syndrome.",
    "A chest radiograph demonstrating lower lobe consolidations consistent with alveolar proteinosis exacerbation.",
    "A chest radiograph revealing multiple small nodules suggestive of pulmonary alveolar microlithiasis.",
    "A chest radiograph showing bilateral, diffuse infiltrates as seen in a rare variant of pulmonary alveolar proteinosis.",
    "A chest radiograph demonstrating patchy ground-glass changes indicative of an uncommon granulomatous lung disease."
]
